COMM_FRT=[
    'userid','feedid','device','authorid','bgm_song_id','bgm_singer_id',
    'videoplayseconds',
    'authorid_count', 
    'vPlaysecBucket_count',
    'authorid_feedid_nunique', 
    'authorid_vPlaysecBucket_nunique',
    'vPlaysecBucket_feedid_nunique', 
    'vPlaysecBucket_authorid_nunique'
]

SELECT_FRTS=[
    'userid','feedid','authorid',
    'device',
    'bgm_song_id','bgm_singer_id',
    'videoplayseconds',#'date_',
    # 'read_comment_feedid_mean',
    # #'read_comment_feedid_sum',
    # 'read_comment_feedid_count',
    # 'like_feedid_mean',
    # #'like_feedid_sum',
    # 'like_feedid_count',
    # 'click_avatar_feedid_mean',
    # #'click_avatar_feedid_sum',
    # 'click_avatar_feedid_count',
    # 'forward_feedid_mean',
    # #'forward_feedid_sum',
    # 'forward_feedid_count',
    # 'comment_feedid_mean',
    # #'comment_feedid_sum',
    # 'comment_feedid_count',
    # 'follow_feedid_mean',
    # #'follow_feedid_sum',
    # 'follow_feedid_count',
    # 'favorite_feedid_mean',
    # #'favorite_feedid_sum',
    # 'favorite_feedid_count',
    # 'read_comment_userid_mean',
    # #'read_comment_userid_sum',
    # 'read_comment_userid_count',
    # 'like_userid_mean',
    # 'like_userid_sum','like_userid_count',
    # 'click_avatar_userid_mean',
    # #'click_avatar_userid_sum',
    # 'click_avatar_userid_count','forward_userid_mean',
    # #'forward_userid_sum',
    # 'forward_userid_count',
    # 'comment_userid_mean',
    # #'comment_userid_sum',
    # 'comment_userid_count',
    # 'follow_userid_mean',
    # #'follow_userid_sum',
    # 'follow_userid_count',
    # 'favorite_userid_mean',
    # #'favorite_userid_sum',
    # 'favorite_userid_count',
    # 'authorid_count',
    # 'vPlaysecBucket_count',
    # 'authorid_feedid_nunique',
    # 'authorid_vPlaysecBucket_nunique',
    # 'vPlaysecBucket_feedid_nunique',
    # 'vPlaysecBucket_authorid_nunique'
    ]
#
DENSE_FEATURE=['videoplayseconds',
    # 'read_comment_feedid_mean',
    # #'read_comment_feedid_sum',
    # 'read_comment_feedid_count',
    # 'like_feedid_mean',
    # #'like_feedid_sum',
    # 'like_feedid_count',
    # 'click_avatar_feedid_mean',
    # #'click_avatar_feedid_sum',
    # 'click_avatar_feedid_count',
    # 'forward_feedid_mean',
    # #'forward_feedid_sum',
    # 'forward_feedid_count',
    # 'comment_feedid_mean',
    # #'comment_feedid_sum',
    # 'comment_feedid_count',
    # 'follow_feedid_mean',
    # #'follow_feedid_sum',
    # 'follow_feedid_count',
    # 'favorite_feedid_mean',
    # #'favorite_feedid_sum',
    # 'favorite_feedid_count',
    # 'read_comment_userid_mean',
    # #'read_comment_userid_sum',
    # 'read_comment_userid_count',
    # 'like_userid_mean',
    # 'like_userid_sum','like_userid_count',
    # 'click_avatar_userid_mean',
    # #'click_avatar_userid_sum',
    # 'click_avatar_userid_count','forward_userid_mean',
    # #'forward_userid_sum',
    # 'forward_userid_count',
    # 'comment_userid_mean',
    # #'comment_userid_sum',
    # 'comment_userid_count',
    # 'follow_userid_mean',
    # #'follow_userid_sum',
    # 'follow_userid_count',
    # 'favorite_userid_mean',
    # #'favorite_userid_sum',
    # 'favorite_userid_count',
    # 'authorid_count',
    # 'vPlaysecBucket_count',
    # 'authorid_feedid_nunique',
    # 'authorid_vPlaysecBucket_nunique',
    # 'vPlaysecBucket_feedid_nunique',
    # 'vPlaysecBucket_authorid_nunique'
    ]
TH_SELECT_FRTS = ['userid', 'feedid', 'date_', 'device', 'authorid',
                  'videoplayseconds', ]#'userid_5day_count', 'userid_5day_finish_rate', 'userid_5day_play_times_max', 'userid_5day_play_times_mean', 'userid_5day_play_max', 'userid_5day_play_mean', 'userid_5day_stay_max', 'userid_5day_stay_mean', 'userid_5day_read_comment_sum', 'userid_5day_read_comment_mean', 'userid_5day_read_comment_count', 'userid_5day_like_sum', 'userid_5day_like_mean', 'userid_5day_like_count', 'userid_5day_click_avatar_sum', 'userid_5day_click_avatar_mean', 'userid_5day_click_avatar_count', 'userid_5day_forward_sum', 'userid_5day_forward_mean', 'userid_5day_forward_count', 'userid_untilnow_read_comment_count', 'userid_untilnow_read_comment_mean', 'userid_untilnow_like_count', 'userid_untilnow_like_mean', 'userid_untilnow_click_avatar_count', 'userid_untilnow_click_avatar_mean', 'userid_untilnow_forward_count', 'userid_untilnow_forward_mean', 'userid_untilnow_read_comment_rate', 'userid_untilnow_read_comment_rate_diff', 'userid_untilnow_read_comment_rate_diff_med', 'userid_untilnow_like_rate', 'userid_untilnow_like_rate_diff', 'userid_untilnow_like_rate_diff_med', 'userid_untilnow_click_avatar_rate', 'userid_untilnow_click_avatar_rate_diff', 'userid_untilnow_click_avatar_rate_diff_med', 'userid_untilnow_forward_rate', 'userid_untilnow_forward_rate_diff', 'userid_untilnow_forward_rate_diff_med', 'feedid_5day_count', 'feedid_5day_finish_rate', 'feedid_5day_play_times_max', 'feedid_5day_play_times_mean', 'feedid_5day_play_max', 'feedid_5day_play_mean', 'feedid_5day_stay_max', 'feedid_5day_stay_mean', 'feedid_5day_read_comment_sum', 'feedid_5day_read_comment_mean', 'feedid_5day_read_comment_count', 'feedid_5day_like_sum', 'feedid_5day_like_mean', 'feedid_5day_like_count', 'feedid_5day_click_avatar_sum', 'feedid_5day_click_avatar_mean', 'feedid_5day_click_avatar_count', 'feedid_5day_forward_sum', 'feedid_5day_forward_mean', 'feedid_5day_forward_count', 'feedid_untilnow_read_comment_count', 'feedid_untilnow_read_comment_mean', 'feedid_untilnow_like_count', 'feedid_untilnow_like_mean', 'feedid_untilnow_click_avatar_count', 'feedid_untilnow_click_avatar_mean', 'feedid_untilnow_forward_count', 'feedid_untilnow_forward_mean', 'feedid_untilnow_read_comment_rate', 'feedid_untilnow_read_comment_rate_diff', 'feedid_untilnow_read_comment_rate_diff_med', 'feedid_untilnow_like_rate', 'feedid_untilnow_like_rate_diff', 'feedid_untilnow_like_rate_diff_med', 'feedid_untilnow_click_avatar_rate', 'feedid_untilnow_click_avatar_rate_diff', 'feedid_untilnow_click_avatar_rate_diff_med', 'feedid_untilnow_forward_rate', 'feedid_untilnow_forward_rate_diff', 'feedid_untilnow_forward_rate_diff_med', 'authorid_5day_count', 'authorid_5day_finish_rate', 'authorid_5day_play_times_max', 'authorid_5day_play_times_mean', 'authorid_5day_play_max', 'authorid_5day_play_mean', 'authorid_5day_stay_max', 'authorid_5day_stay_mean', 'authorid_5day_read_comment_sum', 'authorid_5day_read_comment_mean', 'authorid_5day_read_comment_count', 'authorid_5day_like_sum', 'authorid_5day_like_mean', 'authorid_5day_like_count', 'authorid_5day_click_avatar_sum', 'authorid_5day_click_avatar_mean', 'authorid_5day_click_avatar_count', 'authorid_5day_forward_sum', 'authorid_5day_forward_mean', 'authorid_5day_forward_count', 'authorid_untilnow_read_comment_count', 'authorid_untilnow_read_comment_mean', 'authorid_untilnow_like_count', 'authorid_untilnow_like_mean', 'authorid_untilnow_click_avatar_count', 'authorid_untilnow_click_avatar_mean', 'authorid_untilnow_forward_count', 'authorid_untilnow_forward_mean', 'authorid_untilnow_read_comment_rate', 'authorid_untilnow_read_comment_rate_diff', 'authorid_untilnow_read_comment_rate_diff_med', 'authorid_untilnow_like_rate', 'authorid_untilnow_like_rate_diff', 'authorid_untilnow_like_rate_diff_med', 'authorid_untilnow_click_avatar_rate', 'authorid_untilnow_click_avatar_rate_diff', 'authorid_untilnow_click_avatar_rate_diff_med', 'authorid_untilnow_forward_rate', 'authorid_untilnow_forward_rate_diff', 'authorid_untilnow_forward_rate_diff_med', 'userid_authorid_5day_count', 'userid_authorid_5day_finish_rate', 'userid_authorid_5day_play_times_max', 'userid_authorid_5day_play_times_mean', 'userid_authorid_5day_play_max', 'userid_authorid_5day_play_mean', 'userid_authorid_5day_stay_max', 'userid_authorid_5day_stay_mean', 'userid_authorid_5day_read_comment_sum', 'userid_authorid_5day_read_comment_mean', 'userid_authorid_5day_read_comment_count', 'userid_authorid_5day_like_sum', 'userid_authorid_5day_like_mean', 'userid_authorid_5day_like_count', 'userid_authorid_5day_click_avatar_sum', 'userid_authorid_5day_click_avatar_mean', 'userid_authorid_5day_click_avatar_count',
                 # ] # 'userid_authorid_5day_forward_sum', 'userid_authorid_5day_forward_mean', 'userid_authorid_5day_forward_count', 'userid_authorid_untilnow_read_comment_count', 'userid_authorid_untilnow_read_comment_mean', 'userid_authorid_untilnow_like_count', 'userid_authorid_untilnow_like_mean', 'userid_authorid_untilnow_click_avatar_count', 'userid_authorid_untilnow_click_avatar_mean', 'userid_authorid_untilnow_forward_count', 'userid_authorid_untilnow_forward_mean', 'userid_authorid_untilnow_read_comment_rate', 'userid_authorid_untilnow_read_comment_rate_diff', 'userid_authorid_untilnow_read_comment_rate_diff_med', 'userid_authorid_untilnow_like_rate', 'userid_authorid_untilnow_like_rate_diff', 'userid_authorid_untilnow_like_rate_diff_med', 'userid_authorid_untilnow_click_avatar_rate', 'userid_authorid_untilnow_click_avatar_rate_diff', 'userid_authorid_untilnow_click_avatar_rate_diff_med', 'userid_authorid_untilnow_forward_rate', 'userid_authorid_untilnow_forward_rate_diff', 'userid_authorid_untilnow_forward_rate_diff_med', 'userid_feedid_untilnow_read_comment_rate_add', 'userid_feedid_untilnow_read_comment_rate_mult', 'userid_feedid_untilnow_like_rate_add', 'userid_feedid_untilnow_like_rate_mult', 'userid_feedid_untilnow_click_avatar_rate_add', 'userid_feedid_untilnow_click_avatar_rate_mult', 'userid_feedid_untilnow_forward_rate_add', 'userid_feedid_untilnow_forward_rate_mult', 'feedid_authorid_untilnow_read_comment_rate_add', 'feedid_authorid_untilnow_read_comment_rate_mult', 'feedid_authorid_untilnow_like_rate_add', 'feedid_authorid_untilnow_like_rate_mult', 'feedid_authorid_untilnow_click_avatar_rate_add', 'feedid_authorid_untilnow_click_avatar_rate_mult', 'feedid_authorid_untilnow_forward_rate_add', 'feedid_authorid_untilnow_forward_rate_mult', 'userid_authorid_untilnow_read_comment_rate_add', 'userid_authorid_untilnow_read_comment_rate_mult', 'userid_authorid_untilnow_like_rate_add', 'userid_authorid_untilnow_like_rate_mult', 'userid_authorid_untilnow_click_avatar_rate_add', 'userid_authorid_untilnow_click_avatar_rate_mult', 'userid_authorid_untilnow_forward_rate_add', 'userid_authorid_untilnow_forward_rate_mult', 'userid_count', 'feedid_count', 'authorid_count', 'userid_in_feedid_nunique', 'feedid_in_userid_nunique', 'userid_in_authorid_nunique', 'authorid_in_userid_nunique', 'userid_authorid_count', 'userid_in_authorid_count_prop', 'authorid_in_userid_count_prop', 'videoplayseconds_in_userid_mean', 'videoplayseconds_in_userid_mean_diff_himself', 'videoplayseconds_in_authorid_mean', 'feedid_in_authorid_nunique']

TH_DENSE_FEATURE = [ 'videoplayseconds',]
                     # 'userid_5day_count', 'userid_5day_finish_rate', 'userid_5day_play_times_max', 'userid_5day_play_times_mean', 'userid_5day_play_max', 'userid_5day_play_mean', 'userid_5day_stay_max', 'userid_5day_stay_mean', 'userid_5day_read_comment_sum', 'userid_5day_read_comment_mean', 'userid_5day_read_comment_count', 'userid_5day_like_sum', 'userid_5day_like_mean', 'userid_5day_like_count', 'userid_5day_click_avatar_sum', 'userid_5day_click_avatar_mean', 'userid_5day_click_avatar_count', 'userid_5day_forward_sum', 'userid_5day_forward_mean', 'userid_5day_forward_count', 'userid_untilnow_read_comment_count', 'userid_untilnow_read_comment_mean', 'userid_untilnow_like_count', 'userid_untilnow_like_mean', 'userid_untilnow_click_avatar_count', 'userid_untilnow_click_avatar_mean', 'userid_untilnow_forward_count', 'userid_untilnow_forward_mean', 'userid_untilnow_read_comment_rate', 'userid_untilnow_read_comment_rate_diff', 'userid_untilnow_read_comment_rate_diff_med', 'userid_untilnow_like_rate', 'userid_untilnow_like_rate_diff', 'userid_untilnow_like_rate_diff_med', 'userid_untilnow_click_avatar_rate', 'userid_untilnow_click_avatar_rate_diff', 'userid_untilnow_click_avatar_rate_diff_med', 'userid_untilnow_forward_rate', 'userid_untilnow_forward_rate_diff', 'userid_untilnow_forward_rate_diff_med', 'feedid_5day_count', 'feedid_5day_finish_rate', 'feedid_5day_play_times_max', 'feedid_5day_play_times_mean', 'feedid_5day_play_max', 'feedid_5day_play_mean', 'feedid_5day_stay_max', 'feedid_5day_stay_mean', 'feedid_5day_read_comment_sum', 'feedid_5day_read_comment_mean', 'feedid_5day_read_comment_count', 'feedid_5day_like_sum', 'feedid_5day_like_mean', 'feedid_5day_like_count', 'feedid_5day_click_avatar_sum', 'feedid_5day_click_avatar_mean', 'feedid_5day_click_avatar_count', 'feedid_5day_forward_sum', 'feedid_5day_forward_mean', 'feedid_5day_forward_count', 'feedid_untilnow_read_comment_count', 'feedid_untilnow_read_comment_mean', 'feedid_untilnow_like_count', 'feedid_untilnow_like_mean', 'feedid_untilnow_click_avatar_count', 'feedid_untilnow_click_avatar_mean', 'feedid_untilnow_forward_count', 'feedid_untilnow_forward_mean', 'feedid_untilnow_read_comment_rate', 'feedid_untilnow_read_comment_rate_diff', 'feedid_untilnow_read_comment_rate_diff_med', 'feedid_untilnow_like_rate', 'feedid_untilnow_like_rate_diff', 'feedid_untilnow_like_rate_diff_med', 'feedid_untilnow_click_avatar_rate', 'feedid_untilnow_click_avatar_rate_diff', 'feedid_untilnow_click_avatar_rate_diff_med', 'feedid_untilnow_forward_rate', 'feedid_untilnow_forward_rate_diff', 'feedid_untilnow_forward_rate_diff_med', 'authorid_5day_count', 'authorid_5day_finish_rate', 'authorid_5day_play_times_max', 'authorid_5day_play_times_mean', 'authorid_5day_play_max', 'authorid_5day_play_mean', 'authorid_5day_stay_max', 'authorid_5day_stay_mean', 'authorid_5day_read_comment_sum', 'authorid_5day_read_comment_mean', 'authorid_5day_read_comment_count', 'authorid_5day_like_sum', 'authorid_5day_like_mean', 'authorid_5day_like_count', 'authorid_5day_click_avatar_sum', 'authorid_5day_click_avatar_mean', 'authorid_5day_click_avatar_count', 'authorid_5day_forward_sum', 'authorid_5day_forward_mean', 'authorid_5day_forward_count', 'authorid_untilnow_read_comment_count', 'authorid_untilnow_read_comment_mean', 'authorid_untilnow_like_count', 'authorid_untilnow_like_mean', 'authorid_untilnow_click_avatar_count', 'authorid_untilnow_click_avatar_mean', 'authorid_untilnow_forward_count', 'authorid_untilnow_forward_mean', 'authorid_untilnow_read_comment_rate', 'authorid_untilnow_read_comment_rate_diff', 'authorid_untilnow_read_comment_rate_diff_med', 'authorid_untilnow_like_rate', 'authorid_untilnow_like_rate_diff', 'authorid_untilnow_like_rate_diff_med', 'authorid_untilnow_click_avatar_rate', 'authorid_untilnow_click_avatar_rate_diff', 'authorid_untilnow_click_avatar_rate_diff_med', 'authorid_untilnow_forward_rate', 'authorid_untilnow_forward_rate_diff', 'authorid_untilnow_forward_rate_diff_med', 'userid_authorid_5day_count', 'userid_authorid_5day_finish_rate', 'userid_authorid_5day_play_times_max', 'userid_authorid_5day_play_times_mean', 'userid_authorid_5day_play_max', 'userid_authorid_5day_play_mean', 'userid_authorid_5day_stay_max', 'userid_authorid_5day_stay_mean', 'userid_authorid_5day_read_comment_sum', 'userid_authorid_5day_read_comment_mean', 'userid_authorid_5day_read_comment_count', 'userid_authorid_5day_like_sum', 'userid_authorid_5day_like_mean', 'userid_authorid_5day_like_count', 'userid_authorid_5day_click_avatar_sum', 'userid_authorid_5day_click_avatar_mean', 'userid_authorid_5day_click_avatar_count',
                    # ] # 'userid_authorid_5day_forward_sum', 'userid_authorid_5day_forward_mean', 'userid_authorid_5day_forward_count', 'userid_authorid_untilnow_read_comment_count', 'userid_authorid_untilnow_read_comment_mean', 'userid_authorid_untilnow_like_count', 'userid_authorid_untilnow_like_mean', 'userid_authorid_untilnow_click_avatar_count', 'userid_authorid_untilnow_click_avatar_mean', 'userid_authorid_untilnow_forward_count', 'userid_authorid_untilnow_forward_mean', 'userid_authorid_untilnow_read_comment_rate', 'userid_authorid_untilnow_read_comment_rate_diff', 'userid_authorid_untilnow_read_comment_rate_diff_med', 'userid_authorid_untilnow_like_rate', 'userid_authorid_untilnow_like_rate_diff', 'userid_authorid_untilnow_like_rate_diff_med', 'userid_authorid_untilnow_click_avatar_rate', 'userid_authorid_untilnow_click_avatar_rate_diff', 'userid_authorid_untilnow_click_avatar_rate_diff_med', 'userid_authorid_untilnow_forward_rate', 'userid_authorid_untilnow_forward_rate_diff', 'userid_authorid_untilnow_forward_rate_diff_med', 'userid_feedid_untilnow_read_comment_rate_add', 'userid_feedid_untilnow_read_comment_rate_mult', 'userid_feedid_untilnow_like_rate_add', 'userid_feedid_untilnow_like_rate_mult', 'userid_feedid_untilnow_click_avatar_rate_add', 'userid_feedid_untilnow_click_avatar_rate_mult', 'userid_feedid_untilnow_forward_rate_add', 'userid_feedid_untilnow_forward_rate_mult', 'feedid_authorid_untilnow_read_comment_rate_add', 'feedid_authorid_untilnow_read_comment_rate_mult', 'feedid_authorid_untilnow_like_rate_add', 'feedid_authorid_untilnow_like_rate_mult', 'feedid_authorid_untilnow_click_avatar_rate_add', 'feedid_authorid_untilnow_click_avatar_rate_mult', 'feedid_authorid_untilnow_forward_rate_add', 'feedid_authorid_untilnow_forward_rate_mult', 'userid_authorid_untilnow_read_comment_rate_add', 'userid_authorid_untilnow_read_comment_rate_mult', 'userid_authorid_untilnow_like_rate_add', 'userid_authorid_untilnow_like_rate_mult', 'userid_authorid_untilnow_click_avatar_rate_add', 'userid_authorid_untilnow_click_avatar_rate_mult', 'userid_authorid_untilnow_forward_rate_add', 'userid_authorid_untilnow_forward_rate_mult', 'userid_count', 'feedid_count', 'authorid_count', 'userid_in_feedid_nunique', 'feedid_in_userid_nunique', 'userid_in_authorid_nunique', 'authorid_in_userid_nunique', 'userid_authorid_count', 'userid_in_authorid_count_prop', 'authorid_in_userid_count_prop', 'videoplayseconds_in_userid_mean', 'videoplayseconds_in_userid_mean_diff_himself', 'videoplayseconds_in_authorid_mean', 'feedid_in_authorid_nunique']
WB_DENSE = ['userid', 'feedid',
 'userid_5day_count', 'userid_5day_finish_rate', 'userid_5day_play_times_max', 'userid_5day_play_times_mean',
 'userid_5day_play_max', 'userid_5day_play_mean', 'userid_5day_stay_max', 'userid_5day_stay_mean',
 'userid_5day_read_comment_sum', 'userid_5day_read_comment_mean', 'userid_5day_read_comment_count',
 'userid_5day_like_sum', 'userid_5day_like_mean', 'userid_5day_like_count', 'userid_5day_click_avatar_sum',
 'userid_5day_click_avatar_mean', 'userid_5day_click_avatar_count', 'userid_5day_forward_sum', 'userid_5day_forward_mean',
 'userid_5day_forward_count', 'feedid_5day_count', 'feedid_5day_finish_rate', 'feedid_5day_play_times_max',
 'feedid_5day_play_times_mean', 'feedid_5day_play_max', 'feedid_5day_play_mean', 'feedid_5day_stay_max',
 'feedid_5day_stay_mean', 'feedid_5day_read_comment_sum', 'feedid_5day_read_comment_mean', 'feedid_5day_read_comment_count',
 'feedid_5day_like_sum', 'feedid_5day_like_mean', 'feedid_5day_like_count', 'feedid_5day_click_avatar_sum',
 'feedid_5day_click_avatar_mean', 'feedid_5day_click_avatar_count', 'feedid_5day_forward_sum', 'feedid_5day_forward_mean',
 'feedid_5day_forward_count',  'authorid_5day_count', 'authorid_5day_finish_rate', 'authorid_5day_play_times_max',
 'authorid_5day_play_times_mean', 'authorid_5day_play_max', 'authorid_5day_play_mean', 'authorid_5day_stay_max',
 'authorid_5day_stay_mean', 'authorid_5day_read_comment_sum', 'authorid_5day_read_comment_mean',
 'authorid_5day_read_comment_count', 'authorid_5day_like_sum', 'authorid_5day_like_mean', 'authorid_5day_like_count',
 'authorid_5day_click_avatar_sum', 'authorid_5day_click_avatar_mean', 'authorid_5day_click_avatar_count',
 'authorid_5day_forward_sum', 'authorid_5day_forward_mean', 'authorid_5day_forward_count',
 'userid_authorid_5day_count', 'userid_authorid_5day_finish_rate', 'userid_authorid_5day_play_times_max',
 'userid_authorid_5day_play_times_mean', 'userid_authorid_5day_play_max', 'userid_authorid_5day_play_mean',
 'userid_authorid_5day_stay_max', 'userid_authorid_5day_stay_mean', 'userid_authorid_5day_read_comment_sum',
 'userid_authorid_5day_read_comment_mean', 'userid_authorid_5day_read_comment_count', 'userid_authorid_5day_like_sum',
 'userid_authorid_5day_like_mean', 'userid_authorid_5day_like_count', 'userid_authorid_5day_click_avatar_sum',
 'userid_authorid_5day_click_avatar_mean', 'userid_authorid_5day_click_avatar_count', 'userid_authorid_5day_forward_sum',
 'userid_authorid_5day_forward_mean', 'userid_authorid_5day_forward_count',
 'feedid_in_authorid_nunique', 'userid_5day_read_comment_rate',
 'userid_5day_like_rate', 'userid_5day_click_avatar_rate', 'userid_5day_forward_rate', 'feedid_5day_read_comment_rate',
 'feedid_5day_like_rate', 'feedid_5day_click_avatar_rate', 'feedid_5day_forward_rate',
 'authorid_5day_read_comment_rate', 'authorid_5day_like_rate', 'authorid_5day_click_avatar_rate',
 'authorid_5day_forward_rate', 'userid_authorid_5day_read_comment_rate', 'userid_authorid_5day_like_rate',
 'userid_authorid_5day_click_avatar_rate', 'userid_authorid_5day_forward_rate']

USER_EMB = ['userid_of_feedid_emb_0', 'userid_of_feedid_emb_1',
            'userid_of_feedid_emb_2', 'userid_of_feedid_emb_3', 'userid_of_feedid_emb_4',
            'userid_of_feedid_emb_5', 'userid_of_feedid_emb_6', 'userid_of_feedid_emb_7',
            'userid_of_feedid_emb_adjust_0', 'userid_of_feedid_emb_adjust_1', 'userid_of_feedid_emb_adjust_2',
            'userid_of_feedid_emb_adjust_3', 'userid_of_feedid_emb_adjust_4', 'userid_of_feedid_emb_adjust_5',
            'userid_of_feedid_emb_adjust_6', 'userid_of_feedid_emb_adjust_7']
AUTHOP_EMB=['authorid_manual_tag_emb_0', 'authorid_manual_tag_emb_1', 'authorid_manual_tag_emb_2',
            'authorid_manual_tag_emb_3', 'authorid_manual_tag_emb_4', 'authorid_manual_tag_emb_5',
            'authorid_manual_tag_emb_6', 'authorid_manual_tag_emb_7']
FEED_EMB=['feedid_emb_0', 'feedid_emb_1', 'feedid_emb_2', 'feedid_emb_3', 'feedid_emb_4',
          'feedid_emb_5', 'feedid_emb_6', 'feedid_emb_7']

